<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccessController:index' => function () {
    return ($this->privates['service_locator.S59djr1'] ?? $this->load(__DIR__.'/getServiceLocator_S59djr1Service.php'));
}, 'App\\Controller\\AccessController:register' => function () {
    return ($this->privates['service_locator.d18lq55'] ?? $this->load(__DIR__.'/getServiceLocator_D18lq55Service.php'));
}, 'App\\Controller\\AdminController:add_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController:admin_update_password' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController:admin_users' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController:edit_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\PagesController:mda_2letter' => function () {
    return ($this->privates['service_locator.N6UULWT'] ?? $this->load(__DIR__.'/getServiceLocator_N6UULWTService.php'));
}, 'App\\Controller\\PagesController:mda_letter' => function () {
    return ($this->privates['service_locator.N6UULWT'] ?? $this->load(__DIR__.'/getServiceLocator_N6UULWTService.php'));
}, 'App\\Controller\\PagesController:print_mda_letter' => function () {
    return ($this->privates['service_locator.N6UULWT'] ?? $this->load(__DIR__.'/getServiceLocator_N6UULWTService.php'));
}, 'App\\Controller\\UserController:update_password' => function () {
    return ($this->privates['service_locator.IwzJ4c9'] ?? $this->load(__DIR__.'/getServiceLocator_IwzJ4c9Service.php'));
}, 'App\\Controller\\AccessController::index' => function () {
    return ($this->privates['service_locator.S59djr1'] ?? $this->load(__DIR__.'/getServiceLocator_S59djr1Service.php'));
}, 'App\\Controller\\AccessController::register' => function () {
    return ($this->privates['service_locator.d18lq55'] ?? $this->load(__DIR__.'/getServiceLocator_D18lq55Service.php'));
}, 'App\\Controller\\AdminController::add_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController::admin_update_password' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController::admin_users' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController::edit_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\PagesController::mda_2letter' => function () {
    return ($this->privates['service_locator.N6UULWT'] ?? $this->load(__DIR__.'/getServiceLocator_N6UULWTService.php'));
}, 'App\\Controller\\PagesController::mda_letter' => function () {
    return ($this->privates['service_locator.N6UULWT'] ?? $this->load(__DIR__.'/getServiceLocator_N6UULWTService.php'));
}, 'App\\Controller\\PagesController::print_mda_letter' => function () {
    return ($this->privates['service_locator.N6UULWT'] ?? $this->load(__DIR__.'/getServiceLocator_N6UULWTService.php'));
}, 'App\\Controller\\UserController::update_password' => function () {
    return ($this->privates['service_locator.IwzJ4c9'] ?? $this->load(__DIR__.'/getServiceLocator_IwzJ4c9Service.php'));
})));
