<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \App\Entity\Invoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'mda_code', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_amount', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'training_id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_method', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'initial_invoice', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_status', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_evidence'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'mda_code', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_amount', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'training_id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_method', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_id', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'initial_invoice', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_status', '' . "\0" . 'App\\Entity\\Invoice' . "\0" . 'payment_evidence'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Invoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdaCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdaCode', []);

        return parent::getMdaCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdaCode($mda_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdaCode', [$mda_code]);

        return parent::setMdaCode($mda_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAmount', []);

        return parent::getPaymentAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentAmount($payment_amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentAmount', [$payment_amount]);

        return parent::setPaymentAmount($payment_amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', []);

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod($payment_method)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', [$payment_method]);

        return parent::setPaymentMethod($payment_method);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatus', []);

        return parent::getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentStatus($payment_status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentStatus', [$payment_status]);

        return parent::setPaymentStatus($payment_status);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainingId', []);

        return parent::getTrainingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrainingId($training_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrainingId', [$training_id]);

        return parent::setTrainingId($training_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentId($payment_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentId', [$payment_id]);

        return parent::setPaymentId($payment_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialInvoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialInvoice', []);

        return parent::getInitialInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialInvoice($initial_invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialInvoice', [$initial_invoice]);

        return parent::setInitialInvoice($initial_invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentEvidence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentEvidence', []);

        return parent::getPaymentEvidence();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentEvidence($payment_evidence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentEvidence', [$payment_evidence]);

        return parent::setPaymentEvidence($payment_evidence);
    }

}
