<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Training extends \App\Entity\Training implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'venue', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'time', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'training_code', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'registration_fee', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'individual_amount', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'extra_personnel_amount', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'individuals_per_mda', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'letter_content'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'venue', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'time', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'training_code', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'registration_fee', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'individual_amount', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'extra_personnel_amount', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'individuals_per_mda', '' . "\0" . 'App\\Entity\\Training' . "\0" . 'letter_content'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Training $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getVenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVenue', []);

        return parent::getVenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setVenue($venue): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVenue', [$venue]);

        parent::setVenue($venue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTime', []);

        return parent::getTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setTime($time): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTime', [$time]);

        parent::setTime($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualAmount', []);

        return parent::getIndividualAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualAmount($individual_amount): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualAmount', [$individual_amount]);

        parent::setIndividualAmount($individual_amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraPersonnelAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraPersonnelAmount', []);

        return parent::getExtraPersonnelAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraPersonnelAmount($extra_personnel_amount): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraPersonnelAmount', [$extra_personnel_amount]);

        parent::setExtraPersonnelAmount($extra_personnel_amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndividualsPerMda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndividualsPerMda', []);

        return parent::getIndividualsPerMda();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndividualsPerMda($individuals_per_mda): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndividualsPerMda', [$individuals_per_mda]);

        parent::setIndividualsPerMda($individuals_per_mda);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationFee', []);

        return parent::getRegistrationFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationFee($registration_fee): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationFee', [$registration_fee]);

        parent::setRegistrationFee($registration_fee);
    }

    /**
     * {@inheritDoc}
     */
    public function getLetterContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLetterContent', []);

        return parent::getLetterContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setLetterContent($letter_content): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLetterContent', [$letter_content]);

        parent::setLetterContent($letter_content);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainingCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainingCode', []);

        return parent::getTrainingCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrainingCode($training_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrainingCode', [$training_code]);

        return parent::setTrainingCode($training_code);
    }

}
