<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrainingParticipant extends \App\Entity\TrainingParticipant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'training_id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'session_id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'participant_name', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'participant_email', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'participant_phone', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'mda_code', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'invoice_id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'attended'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'training_id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'session_id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'participant_name', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'participant_email', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'participant_phone', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'mda_code', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'invoice_id', '' . "\0" . 'App\\Entity\\TrainingParticipant' . "\0" . 'attended'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrainingParticipant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainingId', []);

        return parent::getTrainingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrainingId($training_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrainingId', [$training_id]);

        return parent::setTrainingId($training_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionId', []);

        return parent::getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessionId($session_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessionId', [$session_id]);

        return parent::setSessionId($session_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipantName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipantName', []);

        return parent::getParticipantName();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipantName($participant_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipantName', [$participant_name]);

        return parent::setParticipantName($participant_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceId', []);

        return parent::getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceId($invoice_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceId', [$invoice_id]);

        return parent::setInvoiceId($invoice_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdaCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdaCode', []);

        return parent::getMdaCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdaCode($mda_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdaCode', [$mda_code]);

        return parent::setMdaCode($mda_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttended()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttended', []);

        return parent::getAttended();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttended($attended)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttended', [$attended]);

        return parent::setAttended($attended);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipantEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipantEmail', []);

        return parent::getParticipantEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipantEmail($participant_email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipantEmail', [$participant_email]);

        return parent::setParticipantEmail($participant_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipantPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipantPhone', []);

        return parent::getParticipantPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipantPhone($participant_phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipantPhone', [$participant_phone]);

        return parent::setParticipantPhone($participant_phone);
    }

}
