<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRxRumT\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRxRumT/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXRxRumT.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerXRxRumT\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerXRxRumT\srcProdProjectContainer();
